//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmutTanesiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int messageId { get; set; }
        public int senderId { get; set; }
        public System.DateTime messageTime { get; set; }
        public string currentMessage { get; set; }
        public int reciverId { get; set; }
    
        public virtual Users User { get; set; }
        public virtual Users User1 { get; set; }
    }
}
